### ISSUE TITLE
Cubit package moved into BloC

### ISSUE THREAD

**Issue by CodingDavid8** [md-weber/state_tutorials#4]
Regarding your tutorial on the Cubit pattern, I think it would be wise to update the cubit_solution branch.

As far as I know, Cubit is now the official successor of the Bloc package and the cubit package itself can't even be found on pub.dev. Also, some of the structure has changed (Transitions are called Changes when using the bloc package and when the state of a Cubit is modified).

Followingly, your cubit_solution branch is currently deprecated.
I'll create a pull request with a new solution using the BloC package and would be very happy if you could approve & merge it.

Cheers!
-David

**Comment by md-weber** [comment]
Hi David,

that would be great thank you very much!

**Comment by CodingDavid8** [comment]
Hey Max,
I'm happy to help :D 👍 

You can already merge my pull request #5 💯 
Enjoy your week!
